export type CxsmoProduct = {
  id: string;
  drop: string;
  name: string;
  category: "Denim" | "Bottoms" | "Graphics" | "Outerwear" | "Tailoring" | "Accessories" | "Footwear" | "Beauty" | "Lifestyle";
  color: string;
  price: number;
  image: string;
  description: string;
  fit: string;
  details: string[];
};

export const cxsmoCategories = ["All", "New drop", "Denim", "Bottoms", "Graphics", "Outerwear", "Tailoring", "Accessories", "Footwear", "Beauty", "Lifestyle"] as const;

export const cxsmoProducts: CxsmoProduct[] = [
  {
    id: "gravity-01",
    drop: "01",
    name: "Gravity Puddle Jean",
    category: "Denim",
    color: "Static Grey",
    price: 184,
    image: "/manus-storage/cxsmo-gravity-jean-v3_abb22ebf.png",
    description: "Low-slung volume, a long break, and a washed graphite surface that catches light in motion.",
    fit: "Ultra-relaxed, puddle-length leg",
    details: ["12.5 oz washed denim", "Curved outseam", "Chrome star-loop charm"],
  },
  {
    id: "orbit-02",
    drop: "02",
    name: "Orbit Ringer Tee",
    category: "Graphics",
    color: "Milk / Ink",
    price: 76,
    image: "/manus-storage/cxsmo-orbit-tee-v3_20bdb89a.png",
    description: "A close-but-not-tight ringer tee with a small orbital star print and soft, worn-in ribbing.",
    fit: "Fitted shoulder, easy body",
    details: ["Cotton rib jersey", "Contrast binding", "Original star-orbit graphic"],
  },
  {
    id: "starlight-03",
    drop: "03",
    name: "Starlight Moto Shell",
    category: "Outerwear",
    color: "Night Chrome",
    price: 268,
    image: "/manus-storage/cxsmo-starlight-shell-alpha-fallback_a7406211.png",
    description: "A boxy outer layer made to sit over a tiny tee or a full jersey stack, with a reflective edge flash.",
    fit: "Cropped, relaxed shoulder",
    details: ["Water-resistant shell", "Polished zip pull", "Removable star patch"],
  },
  {
    id: "signal-04",
    drop: "04",
    name: "Signal Check Overshirt",
    category: "Tailoring",
    color: "Cloud Check",
    price: 162,
    image: "/manus-storage/cxsmo-signal-overshirt-v3_8699feec.png",
    description: "An easy checked layer with a sharper collar, designed to break up a denim-heavy silhouette.",
    fit: "Wide through the body",
    details: ["Brushed check twill", "Softly structured cuff", "Tonal embroidered sleeve"],
  },
  {
    id: "orbit-05",
    drop: "05",
    name: "Orbit Key Charm",
    category: "Accessories",
    color: "Polished Silver",
    price: 34,
    image: "/manus-storage/cxsmo-key-charm-alpha-fallback_3dd702fb.png",
    description: "A compact metal charm designed to hang from a belt loop, bag zipper, or key ring without becoming costume.",
    fit: "One size",
    details: ["Polished metal finish", "Four-point-star silhouette", "Split-ring clasp"],
  },
  {
    id: "tread-06",
    drop: "06",
    name: "Tread Phase Sneaker",
    category: "Footwear",
    color: "Ink / Milk",
    price: 146,
    image: "/manus-storage/cxsmo-tread-phase-sneaker-alpha_d319a0ce.png",
    description: "A low-profile skate-inspired sneaker that grounds an oversized leg with a clean, slightly retro profile.",
    fit: "True to size",
    details: ["Suede-look upper", "Cushioned cupsole", "Reflective heel tab"],
  },
  {
    id: "gloss-07",
    drop: "07",
    name: "Static Bloom Lip Glaze",
    category: "Beauty",
    color: "Clear Chrome",
    price: 22,
    image: "/manus-storage/cxsmo-static-bloom-lip-glaze-alpha_40b6478e.png",
    description: "Clear, glassy shine in a compact tube sized for a front pocket or the corner of a small bag.",
    fit: "One size",
    details: ["C✦SMO beauty-object study", "Pocket-size tube", "No cosmetic claims represented"],
  },
  {
    id: "transit-08",
    drop: "08",
    name: "Transit Camera Bag",
    category: "Lifestyle",
    color: "Soft Black",
    price: 92,
    image: "/manus-storage/cxsmo-transit-bag-v2_fffacd6e.png",
    description: "A slim shoulder bag imagined for film camera, headphones, keys, and the objects that make a fit feel lived-in.",
    fit: "One size",
    details: ["Padded body", "Adjustable webbing strap", "Interior zip pocket"],
  },
  {
    id: "bluestar-09",
    drop: "09",
    name: "Bluestar C✦SMO Jersey",
    category: "Graphics",
    color: "Midnight Blue / Chrome",
    price: 118,
    image: "/manus-storage/cxsmo-bluestar-jersey_1762d5e8.png",
    description: "A mesh jersey with a star-orbit chest graphic and an easy athletic cut made for layering after dark.",
    fit: "Relaxed athletic body",
    details: ["Perforated-mesh study", "V-neck rib finish", "Star-orbit application"],
  },
  {
    id: "blxck-pants-10",
    drop: "10",
    name: "BLXCK UNIV3RSE Pants",
    category: "Denim",
    color: "Black / Mercury",
    price: 214,
    image: "/manus-storage/cxsmo-blxck-universe-pants_bdd10130.png",
    description: "A wide coated trouser with pale contour panels and compact chrome hardware to break up the black.",
    fit: "Long, wide and low-slung",
    details: ["Coated-twill study", "Contrast contour panel", "Metal hardware detail"],
  },
  {
    id: "blxck-simple-11",
    drop: "11",
    name: "BLXCK UNIV3RSE Longsleeve / Simple",
    category: "Graphics",
    color: "Cloud / Black",
    price: 104,
    image: "/manus-storage/cxsmo-blxck-universe-longsleeve-simple_131cb472.png",
    description: "A soft long sleeve with a low-contrast orbit mark and a relaxed sport-layer silhouette.",
    fit: "Oversized sleeve, easy torso",
    details: ["Jersey-knit study", "Orbital chest mark", "Starline sleeve treatment"],
  },
  {
    id: "blxck-heavy-12",
    drop: "12",
    name: "BLXCK UNIV3RSE Longsleeve / Heavy",
    category: "Graphics",
    color: "Optic Milk / Ink",
    price: 136,
    image: "/manus-storage/cxsmo-blxck-universe-longsleeve-heavy_5b6f6634.png",
    description: "A heavyweight graphic long sleeve built around a large orbit strike and wrapped starline sleeves.",
    fit: "Boxy, heavyweight layer",
    details: ["Heavyweight jersey study", "Large orbital transfer", "Continuous sleeve graphic"],
  },
  {
    id: "mercury-belt-13",
    drop: "13",
    name: "Mercury Orbit Belt",
    category: "Accessories",
    color: "Ink / Brushed Chrome",
    price: 68,
    image: "/manus-storage/cxsmo-mercury-orbit-belt_a7333191.png",
    description: "A narrow technical belt with a sculpted orbit buckle and polished metal loops that turns a low-slung fit into its own signal.",
    fit: "Adjustable, one size",
    details: ["Technical leather-look strap", "Orbit buckle with four-point-star cutout", "Chrome cable-loop hardware"],
  },
  {
    id: "chrome-puddle-14",
    drop: "14",
    name: "Chrome Puddle Sweatpant",
    category: "Bottoms",
    color: "Graphite / Mercury",
    price: 158,
    image: "/manus-storage/cxsmo-chrome-puddle-sweatpant_1351e925.png",
    description: "A deliberately oversized fleece sweatpant with a long pooled hem, reflective contour panels, and enough volume to make the shoe line disappear.",
    fit: "Ultra-wide, puddle-length leg",
    details: ["Heavy brushed fleece concept", "Reflective contour piping", "Four-point-star hip tab"],
  },
  {
    id: "lunar-veil-15",
    drop: "15",
    name: "Lunar Veil Eyewear",
    category: "Accessories",
    color: "Chrome / Lilac Smoke",
    price: 112,
    image: "/manus-storage/cxsmo-lunar-veil-eyewear_a4fe1c13.png",
    description: "A wraparound chrome visor imagined as the final cosmetic layer: soft smoke lens, clean silver architecture, no excess.",
    fit: "One size",
    details: ["Sculptural wrap frame", "Smoke-to-lilac lens study", "Chrome star temple detail"],
  },
  {
    id: "redline-moto-16",
    drop: "16",
    name: "Redline Moto Jacket",
    category: "Outerwear",
    color: "Signal Red / Black",
    price: 326,
    image: "/manus-storage/cxsmo-redline-moto-jacket_778ee18f.png",
    description: "A sharp cropped moto jacket with deep black leather, signal-red panel cuts, and bright hardware placed only where the light finds it.",
    fit: "Cropped boxy body, wide sleeve",
    details: ["Leather-look panel construction", "Polished chrome zip hardware", "Tonal star cuff emboss"],
  },
  {
    id: "silver-crown-case-17",
    drop: "17",
    name: "Silver Crown Cosmetic Case",
    category: "Beauty",
    color: "Pearl Chrome / Signal Red",
    price: 74,
    image: "/manus-storage/cxsmo-silver-crown-cosmetic-case_f85dd076.png",
    description: "A compact silver cosmetic case with a raised star-crown closure and a signal-red lining flash.",
    fit: "One size",
    details: ["Pearlescent technical-nylon study", "Chrome star-crown clasp", "Beauty accessory concept"],
  },
];

export const getCxsmoProduct = (id?: string) => cxsmoProducts.find((product) => product.id === id) ?? cxsmoProducts[0];

export const formatCxsmoPrice = (price: number, locale = "en-US", currency: "USD" | "PHP" | "JPY" | "CNY" | "EUR" = "USD") => new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: 0 }).format(price);
