import { preferCxsmoPublicMedia } from "@/lib/cxsmoMedia";

export type CxsmoProduct = {
  id: string;
  drop: string;
  name: string;
  category: "Denim" | "Bottoms" | "Graphics" | "Outerwear" | "Tailoring" | "Accessories" | "Footwear" | "Beauty" | "Lifestyle";
  color: string;
  price: number;
  image: string;
  description: string;
  fit: string;
  details: string[];
};

export const cxsmoCategories = ["All", "New drop", "Denim", "Bottoms", "Graphics", "Outerwear", "Tailoring", "Accessories", "Footwear", "Beauty", "Lifestyle"] as const;

const cxsmoProductSource: CxsmoProduct[] = [
  { id: "gravity-01", drop: "01", name: "Gravity Puddle Jean", category: "Denim", color: "Static Grey", price: 184, image: "/manus-storage/cxsmo-gravity-jean-v3_abb22ebf.png", description: "Low-slung volume, a long break, and a washed graphite surface that catches light in motion.", fit: "Ultra-relaxed, puddle-length leg", details: ["12.5 oz washed denim", "Curved outseam", "Chrome star-loop charm"] },
  { id: "orbit-02", drop: "02", name: "Orbit Ringer Tee", category: "Graphics", color: "Milk / Ink", price: 76, image: "/manus-storage/cxsmo-orbit-tee-v3_20bdb89a.png", description: "A close-but-not-tight ringer tee with a small orbital star print and soft, worn-in ribbing.", fit: "Fitted shoulder, easy body", details: ["Cotton rib jersey", "Contrast binding", "Original star-orbit graphic"] },
  { id: "starlight-03", drop: "03", name: "Starlight Moto Shell", category: "Outerwear", color: "Night Chrome", price: 268, image: "/manus-storage/cxsmo-starlight-shell-alpha-fallback_a7406211.png", description: "A boxy outer layer made to sit over a tiny tee or a full jersey stack, with a reflective edge flash.", fit: "Cropped, relaxed shoulder", details: ["Water-resistant shell", "Polished zip pull", "Removable star patch"] },
  { id: "signal-04", drop: "04", name: "Signal Check Overshirt", category: "Tailoring", color: "Cloud Check", price: 162, image: "/manus-storage/cxsmo-signal-overshirt-v3_8699feec.png", description: "An easy checked layer with a sharper collar, designed to break up a denim-heavy silhouette.", fit: "Wide through the body", details: ["Brushed check twill", "Softly structured cuff", "Tonal embroidered sleeve"] },
  { id: "orbit-05", drop: "05", name: "Orbit Key Charm", category: "Accessories", color: "Polished Silver", price: 34, image: "/manus-storage/cxsmo-key-charm-alpha-fallback_3dd702fb.png", description: "A compact metal charm designed to hang from a belt loop, bag zipper, or key ring without becoming costume.", fit: "One size", details: ["Polished metal finish", "Four-point-star silhouette", "Split-ring clasp"] },
  { id: "tread-06", drop: "06", name: "Tread Phase Sneaker", category: "Footwear", color: "Ink / Milk", price: 146, image: "/manus-storage/cxsmo-tread-phase-sneaker-alpha_d319a0ce.png", description: "A low-profile skate-inspired sneaker that grounds an oversized leg with a clean, slightly retro profile.", fit: "True to size", details: ["Suede-look upper", "Cushioned cupsole", "Reflective heel tab"] },
  { id: "gloss-07", drop: "07", name: "Static Bloom Lip Glaze", category: "Beauty", color: "Clear Chrome", price: 22, image: "/manus-storage/cxsmo-static-bloom-lip-glaze-alpha_40b6478e.png", description: "Clear, glassy shine in a compact tube sized for a front pocket or the corner of a small bag.", fit: "One size", details: ["C✦SMO beauty-object study", "Pocket-size tube", "No cosmetic claims represented"] },
  { id: "transit-08", drop: "08", name: "Transit Camera Bag", category: "Lifestyle", color: "Soft Black", price: 92, image: "/manus-storage/cxsmo-transit-bag-v2_fffacd6e.png", description: "A slim shoulder bag imagined for film camera, headphones, keys, and the objects that make a fit feel lived-in.", fit: "One size", details: ["Padded body", "Adjustable webbing strap", "Interior zip pocket"] },
  { id: "bluestar-09", drop: "09", name: "Bluestar C✦SMO Jersey", category: "Graphics", color: "Midnight Blue / Chrome", price: 118, image: "/manus-storage/cxsmo-bluestar-jersey_1762d5e8.png", description: "A mesh jersey with a star-orbit chest graphic and an easy athletic cut made for layering after dark.", fit: "Relaxed athletic body", details: ["Perforated-mesh study", "V-neck rib finish", "Star-orbit application"] },
  { id: "blxck-pants-10", drop: "10", name: "BLXCK UNIV3RSE Pants", category: "Denim", color: "Black / Mercury", price: 214, image: "/manus-storage/cxsmo-blxck-universe-pants_bdd10130.png", description: "A wide coated trouser with pale contour panels and compact chrome hardware to break up the black.", fit: "Long, wide and low-slung", details: ["Coated-twill study", "Contrast contour panel", "Metal hardware detail"] },
  { id: "blxck-simple-11", drop: "11", name: "BLXCK UNIV3RSE Longsleeve / Simple", category: "Graphics", color: "Cloud / Black", price: 104, image: "/manus-storage/cxsmo-blxck-universe-longsleeve-simple_131cb472.png", description: "A soft long sleeve with a low-contrast orbit mark and a relaxed sport-layer silhouette.", fit: "Oversized sleeve, easy torso", details: ["Jersey-knit study", "Orbital chest mark", "Starline sleeve treatment"] },
  { id: "blxck-heavy-12", drop: "12", name: "BLXCK UNIV3RSE Longsleeve / Heavy", category: "Graphics", color: "Optic Milk / Ink", price: 136, image: "/manus-storage/cxsmo-blxck-universe-longsleeve-heavy_5b6f6634.png", description: "A heavyweight graphic long sleeve built around a large orbit strike and wrapped starline sleeves.", fit: "Boxy, heavyweight layer", details: ["Heavyweight jersey study", "Large orbital transfer", "Continuous sleeve graphic"] },
  { id: "mercury-belt-13", drop: "13", name: "Mercury Orbit Belt", category: "Accessories", color: "Ink / Brushed Chrome", price: 68, image: "/manus-storage/ChatGPTImageAug15,2026,05_33_54PM_9040fa6d.png", description: "A narrow technical belt with a sculpted orbit buckle and polished metal loops that turns a low-slung fit into its own signal.", fit: "Adjustable, one size", details: ["Technical leather-look strap", "Orbit buckle with four-point-star cutout", "Chrome cable-loop hardware"] },
  { id: "chrome-puddle-14", drop: "14", name: "Chrome Puddle Sweatpant", category: "Bottoms", color: "Graphite / Mercury", price: 158, image: "/manus-storage/ChatGPTImageAug15,2026,05_36_41PM_15fc31e0.png", description: "A deliberately oversized fleece sweatpant with a long pooled hem, reflective contour panels, and enough volume to make the shoe line disappear.", fit: "Ultra-wide, puddle-length leg", details: ["Heavy brushed fleece concept", "Reflective contour piping", "Four-point-star hip tab"] },
  { id: "lunar-veil-15", drop: "15", name: "Lunar Veil Eyewear", category: "Accessories", color: "Chrome / Lilac Smoke", price: 112, image: "/manus-storage/ChatGPTImageAug15,2026,05_38_54PM_ceda59d3.png", description: "A wraparound chrome visor imagined as the final cosmetic layer: soft smoke lens, clean silver architecture, no excess.", fit: "One size", details: ["Sculptural wrap frame", "Smoke-to-lilac lens study", "Chrome star temple detail"] },
  { id: "redline-moto-16", drop: "16", name: "Redline Moto Jacket", category: "Outerwear", color: "Signal Red / Black", price: 326, image: "/manus-storage/ChatGPTImageAug15,2026,05_31_19PM_a78e56f6.png", description: "A sharp cropped moto jacket with deep black leather, signal-red panel cuts, and bright hardware placed only where the light finds it.", fit: "Cropped boxy body, wide sleeve", details: ["Leather-look panel construction", "Polished chrome zip hardware", "Tonal star cuff emboss"] },
  { id: "silver-crown-case-17", drop: "17", name: "Silver Crown Crimson Sling Bag", category: "Lifestyle", color: "Pearl Chrome / Signal Red", price: 74, image: "/manus-storage/ChatGPTImageAug15,2026,05_40_56PM_24d03e4f.png", description: "A compact pearl-chrome sling bag with a raised star-crown closure, a signal-red lining flash, and just enough room for the nightly essentials.", fit: "One size, adjustable cross-body strap", details: ["Pearlescent technical-nylon study", "Chrome star-crown clasp", "Adjustable crimson webbing strap"] },
  { id: "stellar-cargo-18", drop: "18", name: "Stellar Cargo Pants", category: "Bottoms", color: "Pearl / Chrome", price: 196, image: "/manus-storage/ChatGPTImageAug15,2026,05_23_24PM_0e3d74d4.png", description: "A high-volume pearl cargo with polished hardware, articulated pockets, and star-shaped details that keep the silhouette sharp from every angle.", fit: "Ultra-relaxed cargo leg, adjustable hem", details: ["Technical pearl nylon study", "Layered utility pockets", "Adjustable bungee cuffs"] },
  { id: "loud-enough-shirt-19", drop: "19", name: "LOUD ENOUGH Longsleeve", category: "Graphics", color: "Ink / Signal Red", price: 128, image: "/manus-storage/cxsmo-loud-enough-y2k-shirt-alpha_a1936a15.png", description: "A sharp graphic long sleeve with a high-contrast C✦SMO print and close-cut base layer fit for building beneath a wide silhouette.", fit: "Fitted base layer, long sleeve", details: ["Transparent graphic-object render", "High-contrast front artwork", "Cuff-length sleeve profile"] },
  { id: "core-tee-40", drop: "40", name: "Core Oval Tee", category: "Graphics", color: "Black / Chrome", price: 72, image: "/images/cxsmo-catalogue-09-core-tee.png", description: "A soft black short sleeve with a compact oval chest mark and a small star pendant styling detail.", fit: "Relaxed, easy body", details: ["Short-sleeve jersey", "Oval chest mark", "Chrome pendant styling"] },
  { id: "starburst-knit-41", drop: "41", name: "Starburst Knit", category: "Graphics", color: "Ink / Bone", price: 142, image: "/images/cxsmo-catalogue-10-starburst-knit.png", description: "A plush black knit built around a blown-out four-point star graphic for an oversized cold-weather layer.", fit: "Oversized, dropped shoulder", details: ["Textured knit", "Overscale star graphic", "Ribbed cuff and hem"] },
  { id: "vector-cargo-42", drop: "42", name: "Vector Cargo Pant", category: "Bottoms", color: "Ink / Chrome", price: 218, image: "/images/cxsmo-catalogue-11-vector-cargo.png", description: "A black cargo pant with layered zips, chain hardware, and long chrome vector panels down the leg.", fit: "Baggy, stacked leg", details: ["Layered cargo pockets", "Chrome vector panels", "Chain hardware"] },
  { id: "wash-cargo-43", drop: "43", name: "Wash Cargo Jean", category: "Denim", color: "Faded Graphite", price: 202, image: "/images/cxsmo-catalogue-12-wash-cargo.png", description: "A washed grey wide-leg jean with layered cargo seams and hanging charm hardware.", fit: "Wide, puddle-length leg", details: ["Washed denim", "Layered cargo seams", "Hanging star charm"] },
  { id: "utility-puddle-44", drop: "44", name: "Utility Puddle Pant", category: "Bottoms", color: "Black / Chrome", price: 224, image: "/images/cxsmo-catalogue-13-utility-puddle.png", description: "A utility-heavy black puddle pant cut with articulated pocket panels and silver star flashes.", fit: "Ultra-wide, pooled hem", details: ["Articulated pockets", "Silver star appliqué", "Technical belt loops"] },
  { id: "race-crew-45", drop: "45", name: "Race Crew", category: "Graphics", color: "Ink / Optic White", price: 134, image: "/images/cxsmo-catalogue-14-race-crew.png", description: "A black-and-white sport crew with a central C✦SMO star graphic and sharp contrast side panels.", fit: "Relaxed crew body", details: ["Contrast panel construction", "Central logo graphic", "Ribbed collar"] },
  { id: "star-beanie-46", drop: "46", name: "Star Beanie", category: "Accessories", color: "Ink / Chrome", price: 46, image: "/images/cxsmo-catalogue-15-star-beanie.png", description: "A compact black knit beanie finished with a single chrome four-point star patch.", fit: "One size", details: ["Rib knit", "Chrome star patch", "Folded cuff"] },
  { id: "orbit-buckle-47", drop: "47", name: "Orbit Buckle Belt", category: "Accessories", color: "Black / Chrome", price: 82, image: "/images/cxsmo-catalogue-16-orbit-buckle-belt.png", description: "A broad black belt with a sculpted silver orbit buckle and centered four-point-star hardware.", fit: "Adjustable, one size", details: ["Wide belt strap", "Sculpted metal buckle", "Four-point-star hardware"] },
  { id: "bolt-raglan-48", drop: "48", name: "Bolt Raglan", category: "Graphics", color: "Milk / Midnight", price: 98, image: "/images/cxsmo-catalogue-20-bolt-raglan.png", description: "A fitted white-and-navy raglan cut with a compact bolt graphic across the chest.", fit: "Fitted base layer", details: ["Contrast raglan sleeve", "Bolt chest graphic", "Soft stretch jersey"] },
  { id: "star-spear-tank-49", drop: "49", name: "Star Spear Tank", category: "Graphics", color: "Optic White / Ink", price: 64, image: "/images/cxsmo-catalogue-21-star-spear-tank.png", description: "A clean white tank with an elongated black star spear running vertically through the front.", fit: "Close body fit", details: ["Rib jersey", "Vertical star graphic", "Sleeveless cut"] },
  { id: "lace-corset-50", drop: "50", name: "Lace Corset Top", category: "Graphics", color: "Black", price: 118, image: "/images/cxsmo-catalogue-22-lace-corset.png", description: "A black structured corset-style top with narrow straps and a lace-up center front.", fit: "Close, structured fit", details: ["Adjustable straps", "Lace-up front", "Panelled construction"] },
  { id: "leather-zip-vest-51", drop: "51", name: "Leather Zip Vest", category: "Outerwear", color: "Black", price: 196, image: "/images/cxsmo-catalogue-23-leather-zip-vest.png", description: "A fitted black zip vest with a high collar and clean moto-inspired shaping.", fit: "Close, sculpted body", details: ["High collar", "Front zip", "Moto shaping"] },
  { id: "star-ruched-top-52", drop: "52", name: "Star Ruched Top", category: "Graphics", color: "Black / Chrome", price: 94, image: "/images/cxsmo-catalogue-24-star-ruched-top.png", description: "A long-sleeve black top with gathered side seams and a large chrome spear-star graphic.", fit: "Fitted, ruched sleeve", details: ["Gathered seam detail", "Chrome star graphic", "Long sleeve"] },
  { id: "web-tie-tank-53", drop: "53", name: "Web Tie Tank", category: "Graphics", color: "Optic White", price: 78, image: "/images/cxsmo-catalogue-25-web-tie-tank.png", description: "A white tie-shoulder tank with a webbed star front print and an adjustable side tie.", fit: "Close body fit", details: ["Tie shoulder", "Web-star print", "Side-tie detail"] },
  { id: "pleated-belt-skirt-54", drop: "54", name: "Pleated Belt Skirt", category: "Bottoms", color: "Black / Chrome", price: 154, image: "/images/cxsmo-catalogue-26-pleated-belt-skirt.png", description: "A black pleated mini skirt layered with utility straps, chrome buckles, and a hanging chain.", fit: "Low-rise mini length", details: ["Pleated shell", "Utility straps", "Chrome chain hardware"] },
  { id: "lace-tiered-skirt-55", drop: "55", name: "Lace Tiered Skirt", category: "Bottoms", color: "Optic White", price: 148, image: "/images/cxsmo-catalogue-27-lace-tiered-skirt.png", description: "A white tiered mini skirt with a lace-look layered hem and small hardware detail.", fit: "Low-rise mini length", details: ["Tiered layers", "Lace-look finish", "Hardware detail"] },
  { id: "stud-cargo-short-56", drop: "56", name: "Stud Cargo Short", category: "Bottoms", color: "Black", price: 126, image: "/images/cxsmo-catalogue-28-stud-cargo-short.png", description: "A compact black cargo short with angled pocket panels, studs, and a wide belt treatment.", fit: "Low-rise, relaxed short", details: ["Cargo pocket", "Stud detail", "Wide belt treatment"] },
  { id: "chain-cargo-short-57", drop: "57", name: "Chain Cargo Short", category: "Bottoms", color: "Black / Chrome", price: 132, image: "/images/cxsmo-catalogue-29-chain-cargo-short.png", description: "A black cargo short with an oversized star charm, layered straps, and silver chain hardware.", fit: "Low-rise, relaxed short", details: ["Layered straps", "Star charm", "Silver chain hardware"] },
  { id: "midnight-star-sweatpant-58", drop: "58", name: "Midnight Star Sweatpant", category: "Bottoms", color: "Midnight / Chrome", price: 172, image: "/images/cxsmo-catalogue-30-midnight-star-sweatpant.png", description: "A navy wide-leg sweatpant marked by tall chrome stars along the outer leg.", fit: "Wide, pooled hem", details: ["Heavy fleece", "Chrome leg graphic", "Drawcord waist"] },
  { id: "midnight-cargo-skirt-60", drop: "60", name: "Midnight Cargo Skirt", category: "Bottoms", color: "Black", price: 186, image: "/images/cxsmo-catalogue-32-midnight-cargo-skirt.png", description: "A long black cargo skirt with layered pockets, straps, and a dense technical silhouette.", fit: "Low-rise maxi length", details: ["Layered cargo pockets", "Technical strap system", "Long panelled hem"] },
  { id: "halo-pile-hoodie-61", drop: "61", name: "Halo Pile Hoodie", category: "Outerwear", color: "Cloud White", price: 238, image: "/images/cxsmo-catalogue-33-halo-pile-hoodie.png", description: "A plush white hooded layer with a soft pile texture and restrained star hardware.", fit: "Oversized hooded fit", details: ["Pile-texture shell", "Deep hood", "Star hardware detail"] },
  { id: "frost-logo-hoodie-62", drop: "62", name: "Frost Logo Hoodie", category: "Graphics", color: "Heather Grey", price: 148, image: "/images/cxsmo-catalogue-34-frost-logo-hoodie.png", description: "A heather grey hoodie with a large tonal C✦SMO front logo and an oversized dropped shoulder.", fit: "Oversized, dropped shoulder", details: ["Brushed fleece", "Front logo graphic", "Kangaroo pocket"] },
  { id: "buckle-stack-boot-63", drop: "63", name: "Buckle Stack Boot", category: "Footwear", color: "Black", price: 246, image: "/images/cxsmo-catalogue-35-buckle-stack-boot.png", description: "A tall black platform boot with repeated buckle straps and a lugged sole.", fit: "True to size", details: ["Platform lug sole", "Multi-buckle shaft", "Side zip entry"] },
  { id: "cloud-legwarmer-64", drop: "64", name: "Cloud Legwarmer", category: "Accessories", color: "Cloud White", price: 58, image: "/images/cxsmo-catalogue-36-cloud-legwarmer.png", description: "A pair of soft white gathered legwarmers designed to pool over a sneaker or platform boot.", fit: "One size pair", details: ["Soft gathered knit", "Extended length", "Footwear layering piece"] },
  { id: "chrome-charm-bag-65", drop: "65", name: "Chrome Charm Bag", category: "Lifestyle", color: "Black / Chrome", price: 118, image: "/images/cxsmo-catalogue-37-chrome-charm-bag.png", description: "A compact black shoulder bag with a chrome star frame and a plush character charm.", fit: "One size", details: ["Shoulder strap", "Chrome star hardware", "Character charm"] },
  { id: "mercury-headphones-66", drop: "66", name: "Mercury Headphones", category: "Lifestyle", color: "Silver", price: 138, image: "/images/cxsmo-catalogue-38-mercury-headphones.png", description: "A silver over-ear headphone object with a sculpted four-point-star badge on the ear cup.", fit: "One size", details: ["Over-ear form", "Sculpted star badge", "Cushioned ear cups"] },
  { id: "lunar-visor-67", drop: "67", name: "Lunar Visor", category: "Accessories", color: "Black / Chrome", price: 96, image: "/images/cxsmo-catalogue-39-lunar-visor.png", description: "A narrow black visor with a small silver star mark at the temple.", fit: "One size", details: ["Wrap visor frame", "Star temple mark", "Dark lens"] },
  { id: "black-star-overshirt-68", drop: "68", name: "Black Star Overshirt", category: "Outerwear", color: "Washed Black / Bone", price: 168, image: "/images/cxsmo-clean-overshirt-01.png", description: "A black oversized button-up overshirt with dense bone-white star marks across the chest and sleeves.", fit: "Relaxed, boxy layer", details: ["Button-front construction", "Washed black fabric", "All-over star marks"] },
  { id: "white-star-hood-69", drop: "69", name: "White Star Hood", category: "Outerwear", color: "Cloud / Ink", price: 182, image: "/images/cxsmo-clean-zip-hoodie-02.png", description: "A white zip hood with pointed black star graphics and a soft washed technical finish.", fit: "Oversized hooded fit", details: ["Zip front", "Star sleeve graphic", "Adjustable hood"] },
  { id: "spear-rib-tank-70", drop: "70", name: "Spear Rib Tank", category: "Graphics", color: "Black / Bone", price: 68, image: "/images/cxsmo-clean-star-tank-03.png", description: "A fitted black rib tank with an elongated pale star spear and gathered side seams.", fit: "Close body fit", details: ["Rib jersey", "Elongated star emblem", "Ruched side seam"] },
  { id: "washed-star-hood-71", drop: "71", name: "Washed Star Hood", category: "Outerwear", color: "Charcoal / Bone", price: 188, image: "/images/cxsmo-clean-hooded-jacket-04.png", description: "A washed charcoal hooded zip layer cut loose with pale star-flame sleeve graphics.", fit: "Loose hooded fit", details: ["Washed shell", "Zip front", "Star-flame sleeves"] },
  { id: "contrast-halfzip-72", drop: "72", name: "Contrast Halfzip", category: "Graphics", color: "Optic / Black", price: 122, image: "/images/cxsmo-clean-contrast-halfzip-05.png", description: "A sharp white half-zip with black side panels, striped sleeves, and a center star mark.", fit: "Relaxed sport layer", details: ["Half-zip collar", "Contrast sleeve panel", "Chest star graphic"] },
  { id: "flame-star-crew-73", drop: "73", name: "Flame Star Crew", category: "Graphics", color: "Black / Bone", price: 136, image: "/images/cxsmo-clean-star-crew-06.png", description: "A black oversized crew marked by a centered star and flame-like sleeve graphics.", fit: "Oversized crew body", details: ["Heavy fleece", "Center star graphic", "Graphic sleeves"] },
  { id: "washed-orbit-knit-74", drop: "74", name: "Washed Orbit Knit", category: "Graphics", color: "Ash / Bone", price: 148, image: "/images/cxsmo-clean-washed-star-knit-07.png", description: "A distressed grey knit with an oversized pale orbit-star graphic.", fit: "Relaxed knit body", details: ["Washed knit", "Overscale star graphic", "Rib trims"] },
  { id: "flame-track-hoodie-75", drop: "75", name: "Flame Track Hoodie", category: "Outerwear", color: "Black / Bone", price: 174, image: "/images/cxsmo-clean-track-hoodie-08.png", description: "A black zip hoodie with bright sleeve flames and star marks, styled as a wide upper layer.", fit: "Relaxed zip hoodie", details: ["Zip front", "Graphic sleeves", "Layered tee insert"] },
  { id: "star-trucker-76", drop: "76", name: "Star Trucker", category: "Outerwear", color: "Charcoal / Bone", price: 192, image: "/images/cxsmo-clean-star-denim-jacket-09.png", description: "A washed charcoal trucker jacket with scattered pale star placements and a cropped boxy body.", fit: "Boxy trucker fit", details: ["Washed denim", "Button front", "Star placements"] },
  { id: "chain-star-moto-77", drop: "77", name: "Chain Star Moto", category: "Outerwear", color: "Black / Bone", price: 268, image: "/images/cxsmo-clean-star-leather-jacket-10.png", description: "A black leather moto jacket with connected star graphics and a sharp structured collar.", fit: "Structured moto fit", details: ["Leather-look shell", "Front zip", "Chain-star graphic"] },
  { id: "star-utility-pack-78", drop: "78", name: "Star Utility Pack", category: "Lifestyle", color: "Black", price: 106, image: "/images/cxsmo-clean-star-pack-11.png", description: "A compact black utility backpack with webbing, buckle details, and small four-point star marks.", fit: "One size", details: ["Multiple pockets", "Adjustable straps", "Technical webbing"] },
  { id: "nocturne-headphones-80", drop: "80", name: "Nocturne Headphones", category: "Lifestyle", color: "Black / Silver", price: 144, image: "/images/cxsmo-clean-headphones-13.png", description: "Black-and-silver over-ear headphones with four-point star badges at the ear cups.", fit: "One size", details: ["Over-ear form", "Star ear-cup badges", "Cushioned headband"] },
  { id: "distressed-star-cap-81", drop: "81", name: "Distressed Star Cap", category: "Accessories", color: "Washed Black / Bone", price: 54, image: "/images/cxsmo-clean-star-cap-14.png", description: "A washed black cap finished with a centered pale four-point star embroidery.", fit: "Adjustable, one size", details: ["Distressed wash", "Star embroidery", "Adjustable back strap"] },
  { id: "star-chain-cargo-82", drop: "82", name: "Star Chain Cargo", category: "Bottoms", color: "Black / Bone", price: 226, image: "/images/cxsmo-clean-star-cargo-15.png", description: "An ultra-wide black cargo pant with silver chain hardware and tall pale star graphics.", fit: "Ultra-wide, pooled hem", details: ["Layered cargo pockets", "Chain hardware", "Tall star graphics"] },
];

export const cxsmoProducts: CxsmoProduct[] = cxsmoProductSource.map((product) => ({ ...product, image: preferCxsmoPublicMedia(product.image) }));

export const getCxsmoProduct = (id?: string) => cxsmoProducts.find((product) => product.id === id) ?? cxsmoProducts[0];

export const formatCxsmoPrice = (price: number, locale = "en-US", currency: "USD" | "PHP" | "JPY" | "CNY" | "EUR" = "USD") => new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: 0 }).format(price);
