import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check, Heart, LogIn, LogOut, MapPin, PackageCheck, ShoppingBag, SlidersHorizontal, Sparkles, UserPlus, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link } from "wouter";
import { CxsmoShell, ProductCard } from "./CxsmoStorefront";
import { useCxsmoDemo } from "@/contexts/CxsmoDemoContext";
import { cxsmoProducts } from "@/lib/cxsmo";
import "./cxsmo-account-hub.css";
import "./cxsmo-account-light-fix.css";

type AccountTab = "overview" | "profile" | "saves" | "activity";
const accountLinks: { id: AccountTab; label: string; href: string }[] = [{ id: "overview", label: "Account home", href: "/cxsmo/account" }, { id: "profile", label: "Profile + taste", href: "/cxsmo/account/profile" }, { id: "saves", label: "Liked objects", href: "/cxsmo/account/saves" }, { id: "activity", label: "Orders + delivery", href: "/cxsmo/account/activity" }];

function AccountRail({ active }: { active: AccountTab }) { return <nav className="cxsmo-account-hub__rail" aria-label="Account destinations">{accountLinks.map((item, index) => <Link className={item.id === active ? "is-active" : ""} href={item.href} key={item.id}><span>0{index + 1}</span>{item.label}<ArrowUpRight size={13} /></Link>)}</nav>; }

function LocalAccountModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { profile, startLocalAccount } = useCxsmoDemo();
  const [handle, setHandle] = useState(profile.displayName);
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!open) return; window.setTimeout(() => closeRef.current?.focus(), 0); const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose, open]);
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); startLocalAccount(handle); onClose(); };
  return <AnimatePresence>{open && <motion.div className="cxsmo-account-modal" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.form role="dialog" aria-modal="true" aria-labelledby="cxsmo-account-entry-title" initial={{ opacity: 0, y: 22, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 15, scale: .98 }} transition={{ duration: .28, ease: [0.16, 1, .3, 1] }} onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><button ref={closeRef} type="button" aria-label="Close account entry" onClick={onClose}><X size={18} /></button><p>LOCAL ACCOUNT / NO CREDENTIALS</p><h2 id="cxsmo-account-entry-title">Set your<br /><em>handle.</em></h2><span>Create or restore a display-only session on this browser. No password, personal data, or account record is sent anywhere.</span><label>Display handle<input autoComplete="nickname" value={handle} onChange={(event) => setHandle(event.target.value)} placeholder="e.g. chromeafterdark" /></label><button className="cxsmo-button" type="submit"><UserPlus size={16} /> Start local session</button></motion.form></motion.div>}</AnimatePresence>;
}

export function CxsmoAccountHomePage() {
  const { bag, savedIds, profile } = useCxsmoDemo();
  const [modalOpen, setModalOpen] = useState(false);
  return <CxsmoShell><section className="cxsmo-account-hub"><div className="cxsmo-account-hub__hero"><div><p>YOUR FREQUENCY / LOCAL DEMO</p><h1>{profile.isSignedIn ? <>Hi, {profile.displayName || "signal"}.<br /><em>Keep it tuned.</em></> : <>Make this<br /><em>your frequency.</em></>}</h1><span>One local control room for saved objects, staged bag choices, profile signals, and future commerce architecture.</span>{profile.isSignedIn ? <Link className="cxsmo-button" href="/cxsmo/account/profile">Open profile <ArrowUpRight size={16} /></Link> : <button className="cxsmo-button" type="button" onClick={() => setModalOpen(true)}><LogIn size={16} /> Create or sign in locally</button>}</div><aside><span>SESSION STATUS</span><b>{profile.isSignedIn ? "Local session active" : "No local session"}</b><p>{profile.isSignedIn ? "Your choices remain on this device for the portfolio demonstration." : "Use a display handle to keep browser-local preferences together."}</p></aside></div><AccountRail active="overview" /><section className="cxsmo-account-hub__tiles"><Link href="/cxsmo/account/saves"><Heart size={20} /><span>Liked objects</span><b>{savedIds.length}</b><p>Keep the shapes worth revisiting.</p></Link><Link href="/cxsmo/bag"><ShoppingBag size={20} /><span>Staged bag</span><b>{bag.length}</b><p>Review the local selection before checkout preview.</p></Link><Link href="/cxsmo/account/activity"><PackageCheck size={20} /><span>Delivery states</span><b>0</b><p>Nothing shipped or simulated as delivered.</p></Link><Link href="/cxsmo/account/profile"><SlidersHorizontal size={20} /><span>Profile signals</span><b>{profile.isConfigured ? "Set" : "—"}</b><p>Taste, fit, locale, and update preference.</p></Link></section><section className="cxsmo-account-hub__message"><Sparkles size={18} /><div><p>ACCOUNT ARCHITECTURE / HONEST MODE</p><h2>A useful shopper surface<br /><em>does not need fake history.</em></h2></div><span>Orders, payments, received items, ratings, and messages stay empty until a real, consented commerce source exists.</span></section></section><LocalAccountModal open={modalOpen} onClose={() => setModalOpen(false)} /></CxsmoShell>;
}

export function CxsmoAccountProfilePage() {
  const { profile, updateProfile, startLocalAccount, signOutLocalAccount } = useCxsmoDemo();
  const [draft, setDraft] = useState(profile);
  const [saved, setSaved] = useState(false);
  const commit = () => { updateProfile(draft); setSaved(true); window.setTimeout(() => setSaved(false), 1600); };
  return <CxsmoShell><section className="cxsmo-account-hub"><header className="cxsmo-account-hub__pagehead"><p>PROFILE / LOCAL ONLY</p><h1>Dial the<br /><em>signal in.</em></h1><span>These preferences are browser-local and let the portfolio demonstrate a realistic customer setup without creating an identity, order, or delivery record.</span></header><AccountRail active="profile" /><section className="cxsmo-account-hub__form"><label><span><SlidersHorizontal size={15} /> Display handle</span><input value={draft.displayName} onChange={(event) => setDraft({ ...draft, displayName: event.target.value })} placeholder="How should C✦SMO address you?" /></label><label><span><MapPin size={15} /> Delivery preference</span><input value={draft.destination} onChange={(event) => setDraft({ ...draft, destination: event.target.value })} placeholder="City / country — stays in this browser" /></label><div><span>Style frequency</span><section>{(["Signal", "Quiet", "Chrome"] as const).map((mode) => <button type="button" className={draft.styleMode === mode ? "is-active" : ""} onClick={() => setDraft({ ...draft, styleMode: mode })} key={mode}>{mode}</button>)}</section></div><label className="cxsmo-account-hub__toggle"><input type="checkbox" checked={draft.updatesEnabled} onChange={(event) => setDraft({ ...draft, updatesEnabled: event.target.checked })} /><span>Allow a fictional drop-alert preview on this device</span></label><div className="cxsmo-account-hub__form-actions"><button className="cxsmo-button" type="button" onClick={commit}>{saved ? <><Check size={16} /> Preferences saved</> : "Save local preferences"}</button>{profile.isSignedIn ? <button type="button" onClick={signOutLocalAccount}><LogOut size={15} /> Sign out locally</button> : <button type="button" onClick={() => startLocalAccount(draft.displayName)}><UserPlus size={15} /> Start local session</button>}</div></section></section></CxsmoShell>;
}

export function CxsmoAccountSavesPage() {
  const { savedIds } = useCxsmoDemo();
  const saved = cxsmoProducts.filter((product) => savedIds.includes(product.id));
  return <CxsmoShell><section className="cxsmo-account-hub"><header className="cxsmo-account-hub__pagehead"><p>LIKED OBJECTS / LOCAL ONLY</p><h1>Keep the<br /><em>signal close.</em></h1><span>Save an object from the catalogue to build a private browser-local reference rack.</span></header><AccountRail active="saves" /><section className="cxsmo-account-hub__saves">{saved.length ? saved.map((product, index) => <ProductCard product={product} order={`0${index + 1}`} key={product.id} />) : <div className="cxsmo-empty-state"><Heart size={25} /><h2>No likes yet.</h2><p>Use the heart on any object to keep it in this local list.</p><Link className="cxsmo-button" href="/cxsmo/shop">Explore the objects <ArrowDownRight size={16} /></Link></div>}</section></section></CxsmoShell>;
}

export function CxsmoAccountActivityPage() {
  const { bag } = useCxsmoDemo();
  return <CxsmoShell><section className="cxsmo-account-hub"><header className="cxsmo-account-hub__pagehead"><p>ACTIVITY / DATA-READY</p><h1>Nothing shipped.<br /><em>Nothing invented.</em></h1><span>A transparent zero-state makes the line between an interaction prototype and a real shop clear.</span></header><AccountRail active="activity" /><section className="cxsmo-account-hub__activity"><article><span>0 verified orders</span><b>Order history</b><p>Real orders, payment states, and receipts are not simulated in this portfolio.</p></article><article><span>0 active deliveries</span><b>Delivery tracking</b><p>Tracking appears only after a legitimate shipment source exists.</p></article><article><span>{bag.length} staged object{bag.length === 1 ? "" : "s"}</span><b>Bag preview</b><p>Your current browser-local selection can be reviewed without checkout or payment.</p><Link href="/cxsmo/bag">Open local bag <ArrowUpRight size={15} /></Link></article></section></section></CxsmoShell>;
}
