import { Check, MessageCircle, Palette, Plus, WandSparkles } from "lucide-react";
import { FormEvent, useState } from "react";

type Props = { published: boolean; setPublished: (value: boolean) => void };

export function CxsmoStudioContentPanel({ published, setPublished }: Props) {
  const [accent, setAccent] = useState("Signal red");
  const [announcement, setAnnouncement] = useState(true);
  const [draft, setDraft] = useState("");
  const [notes, setNotes] = useState<string[]>([]);
  const addNote = (event: FormEvent) => { event.preventDefault(); const value = draft.trim(); if (!value) return; setNotes((items) => [...items, value]); setDraft(""); };
  return <section className="cx-admin__canvas"><div className="cx-admin__section-head"><div><p className="cx-admin__eyebrow">STOREFRONT STORY / LOCAL WORKSPACE</p><h2>Content room</h2></div><button className="cx-admin__primary"><Plus size={16} /> New story</button></div><div className="cx-admin__content-grid"><article className="cx-admin__content-card"><div><p>Homepage hero</p><span>{published ? "Published in demo" : "Draft state"}</span></div><h3>Street in orbit.</h3><small>Hero title / Drop 01</small><button onClick={() => setPublished(!published)}>{published ? "Move to draft" : "Publish demo state"}</button></article><article className="cx-admin__content-card cx-admin__content-card--blue"><div><p>Fit edit</p><span>Portfolio story</span></div><h3>Wear it your loud.</h3><small>Styling narrative / Issue 01</small><button>Open editor</button></article><article className="cx-admin__content-card cx-admin__content-card--lime"><div><p>Category launch</p><span>Planned</span></div><h3>Beauty + objects.</h3><small>Future category lane</small><button>Prepare draft</button></article></div><div className="cx-admin__cms-grid"><section className="cx-admin__customizer"><div><Palette size={19} /><p>Storefront customization</p><span>Local visual-preview controls only</span></div><label>Campaign accent<select value={accent} onChange={(event) => setAccent(event.target.value)}><option>Signal red</option><option>Chrome bone</option><option>Night ink</option></select></label><label className="cx-admin__toggle-row"><input type="checkbox" checked={announcement} onChange={(event) => setAnnouncement(event.target.checked)} /><span>Show drop announcement in preview</span></label><button type="button"><WandSparkles size={15} /> Stage {accent.toLowerCase()} preview</button></section><section className="cx-admin__workflow-notes"><div><MessageCircle size={19} /><p>Internal workflow notes</p><span>{notes.length} local note{notes.length === 1 ? "" : "s"}</span></div><form onSubmit={addNote}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Add a private production note" /><button type="submit"><Plus size={15} /> Add note</button></form>{notes.length ? <ul>{notes.map((note, index) => <li key={`${note}-${index}`}><Check size={14} /><span>{note}</span></li>)}</ul> : <p className="cx-admin__workflow-empty">No internal notes yet. Add production context here—never fabricated customer comments.</p>}</section></div></section>;
}
